language: node_js
node_js:
  - "8.1.4"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
script:
  - npm run npm-pkg-check
  - npm run lint
  - npm run test:ci
before_deploy:
  - echo "listando arquivos e diretórios:"
  - ls  
  - chmod u+x ./deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on: 
    branch: master
after_deploy: 
  - ls
  - echo "exibindo log do deploy:"
  - cat deploy_log.txt